version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  application:
    image: docker.io/domasm97/domasm:dmasevicius_application
    container_name: application
    ports:
      - "5000:5000"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      BG_COLOR: teal
      FAIL_FLAG: "false"
    depends_on:
      - mongo
